<?php

   define("WPROTECT_HASH_TYPE","sha256");

   //user out str def 
   define("LINK_SQL_ERROR","连接SQL失败,请检查你的配置文件,或运行/install.php进行设置\n");
   define("UNIQUE_USER_ERROR","注册失败,用户名已被注册\n");
   define("ADD_USER_FAIL","注册失败,请检查您的输入信息\n");
   define("ADD_USER_SUCCESS","注册成功,请登录\n");
   define("RESET_PASSWORD_SUCCESS","找回密码成功\n");
   define("RESET_PASSWORD_FAIL","找回密码失败,请检查您的答案是否正确\n");
   define("MODIFY_PASSWORD_SUCCESS","修改密码成功\n");
   define("MODIFY_PASSWORD_FAIL","修改密码失败,请检查您的原密码是否输入正确\n");
   define("LOGIN_SUCCESS","登录成功\n");
   define("LOGIN_FAIL","登录失败\n");
   define("ERROR_PREFIX","错误代码:");
   //end
?>
